### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by arabindo** [jitinnair1/gradfolio#5]
The repository does not have any Gemfile, While trying to build it locally it shows some error! Is there is any solution to build it locally?

**Comment by jitinnair1** [comment]
Try `jekyll serve --incremental`

**Comment by arabindo** [comment]
> Try `jekyll serve --incremental`

Yes tried that, I'm getting the following error!

/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)

**Comment by jitinnair1** [comment]
Have you modified the `url` and `baseurl` fields in `_config.yml`? If so, are you using any special characters there? Also, can you post a screenshot of the error after you run `jekyll serve --incremental`

**Comment by jitinnair1** [comment]
Closing due to inactivity

**Comment by arabnejad** [comment]
Hi @jitinnair1 

I am also getting the similar error :confused: , I did not touch anything, just download the zip folder, extract, and follow your instructions
here is the output log

```sh
Traceback (most recent call last):
	39: from /home/hamid/gems/bin/jekyll:23:in `<main>'
	38: from /home/hamid/gems/bin/jekyll:23:in `load'
	37: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	36: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	35: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	34: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	33: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	32: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	31: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	30: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	29: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	28: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	27: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	26: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	25: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	24: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
	23: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:210:in `render'
	22: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `render_docs'
	21: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `each_value'
	20: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `block in render_docs'
	19: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `each'
	18: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	17: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:548:in `render_regenerated'
	16: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/document.rb:392:in `trigger_hooks'
	15: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `trigger'
	14: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `each'
	13: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:103:in `block in trigger'
	12: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:335:in `block in <top (required)>'
	11: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:35:in `process'
	10: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:65:in `process_html'
	 9: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
	 8: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
	 7: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
	 6: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	 5: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
	 4: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
	 3: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:196:in `external?'
	 2: from /usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	 1: from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:16:in `split': undefined method `to_str' for nil:NilClass (NoMethodError)
	40: from /home/hamid/gems/bin/jekyll:23:in `<main>'
	39: from /home/hamid/gems/bin/jekyll:23:in `load'
	38: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
	37: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	36: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	35: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	34: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	33: from /var/lib/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	32: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	31: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	30: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
	29: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	28: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
	27: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	26: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	25: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
	24: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:210:in `render'
	23: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `render_docs'
	22: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:530:in `each_value'
	21: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `block in render_docs'
	20: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:531:in `each'
	19: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	18: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:548:in `render_regenerated'
	17: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/document.rb:392:in `trigger_hooks'
	16: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `trigger'
	15: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:102:in `each'
	14: from /var/lib/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/hooks.rb:103:in `block in trigger'
	13: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:335:in `block in <top (required)>'
	12: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:35:in `process'
	11: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:65:in `process_html'
	10: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:77:in `process_anchor_tags'
	 9: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
	 8: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
	 7: from /home/hamid/gems/gems/nokogiri-1.11.3-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
	 6: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:78:in `block in process_anchor_tags'
	 5: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:92:in `processable_link?'
	 4: from /home/hamid/gems/gems/jekyll-target-blank-2.0.0/lib/jekyll-target-blank.rb:196:in `external?'
	 3: from /usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	 2: from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
	 1: from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:15:in `split'
/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:18:in `rescue in split': bad URI(is not URI?): nil (URI::InvalidURIError)

```

**Comment by jitinnair1** [comment]
Thanks @arabnejad for pointing this out. My guess is it is a [bug](https://github.com/keithmifsud/jekyll-target-blank/issues/50#issue-579990375) in `jekyll-target-blank`. For now, you can remove `jekyll-target-blank` under plugins in the [`_config.yml`](https://github.com/jitinnair1/gradfolio/blob/38428f35082440e2ea5d11a500e278b102912764/_config.yml#L61)

**Comment by arabnejad** [comment]
THANKS @jitinnair1 :+1:
disabling `jekyll-target-blank` in  the `_config.yml` solve the problem :grin:

**Comment by arabindo** [comment]
Sorry, I was a little busy these days, I couldn't reply. Certainly, I received the mail and tried. It's working now. Thanks to @arabnejad for reopening this issue and obvious thanks to @jitinnair1  for your quick responses!

**Comment by jitinnair1** [comment]
@arabnejad @arabindo So, I figured out what is happening. If the url field is left empty, `jekyll-target-blank` [may throw an error](https://github.com/keithmifsud/jekyll-target-blank/issues/53#issue-754968963). Removing `jekyll-target-blank` is a temporary fix. I'll probably add support for local development environment url to fix this. Thanks for highlighting this issue.
